# Generated by Django 4.1.2 on 2022-10-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('frist_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kabinet.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('datatime', models.DateTimeField()),
                ('last_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kabinet.product')),
            ],
        ),
    ]
