# Generated by Django 4.0.6 on 2022-10-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0002_product_datatime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datatime',
        ),
    ]
